### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by MacFJA** [adhocore/php-polyfills#12]
Hi,

The version required in the `composer.json` make the library useless:

The library is mean to add functions that were added in PHP 5.4 and 5.5, but the minimum version allowed by the `composer.json` is PHP 7.0.0.

So Composer will never (normally) allow to install this library with PHP 5.3 and 5.4

**Comment by adhocore** [comment]
thanks for pointing out. something like `--ignore-platform-reqs` should do. but it is worth fixing as well.
